spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: amq.topic
    routing-key: test.#
    queue: test

  kafka:
    bootstrap-servers: localhost:9092
    topic: kafka-test-topic
    consumer:
      group-id: kafka-group
      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 100

server:
  port: 8080
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.rabbitmq: DEBUG
    org.hibernate.SQL: DEBUG

load:
  test:
    enabled: false
    messages-per-batch: 1000
    batch-interval: 200
    duration-seconds: 60

mqtt:
  broker-url: tcp://localhost:1883
  client-id: client
  topic: test
  qos: 1
  clean-session: false

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus
  endpoint:
    metrics:
      enabled: true