spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  virtual-host: /
  stomp:
    port: 61613
  sensor:
    queue:
      name: sensor.queue
    exchange:
      name: sensor.exchange
    routing:
      key: sensor.data.#

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.rabbitmq: DEBUG