# MQTT \uC124\uC815
mqtt:
  broker:
    url: tcp://localhost:1883
  client:
    id: iotApp
  topic: iot/data
  qos: 1
  clean-session: false

# RabbitMQ \uC124\uC815
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  # \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC124\uC815
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect

# \uC11C\uBC84 \uC124\uC815
server:
  port: 8080
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.rabbitmq: DEBUG
    org.hibernate.SQL: DEBUG

load:
  test:
    enabled: false  # \uAE30\uBCF8 \uBE44\uD65C\uC131\uD654
    messages-per-batch: 5000  # \uCD08\uB2F9(\uBC30\uCE58\uB2F9) \uC804\uC1A1\uD560 \uBA54\uC2DC\uC9C0 \uC218
    batch-interval: 1000  # \uBC30\uCE58 \uAC04\uACA9 (\uB098\uB178\uCD08)
    duration-seconds: 10  # \uD14C\uC2A4\uD2B8 \uC2E4\uD589 \uC2DC\uAC04 (\uCD08)
    resource-check-interval: 5000
